package detect

import (
	"fmt"
	"sort"
	"strings"
)

// GenerateConfig produces a rex.toml content from a Detection result.
func GenerateConfig(d Detection) string {
	var b strings.Builder

	b.WriteString("# rex.toml — generated by rex init\n")
	b.WriteString("# Edit commands below to customize your project.\n\n")

	if d.Stack != "" {
		b.WriteString(fmt.Sprintf("# Detected: %s", d.Stack))
		if d.PkgMgr != "" && d.PkgMgr != d.Stack {
			b.WriteString(fmt.Sprintf(" + %s", d.PkgMgr))
		}
		if len(d.Frameworks) > 0 {
			b.WriteString(fmt.Sprintf(" (%s)", strings.Join(d.Frameworks, ", ")))
		}
		b.WriteString("\n\n")
	}

	b.WriteString("[commands]\n")

	// Sort verbs for consistent output
	verbs := make([]string, 0, len(d.Commands))
	for v := range d.Commands {
		verbs = append(verbs, string(v))
	}
	sort.Strings(verbs)

	for _, v := range verbs {
		cmd := d.Commands[Verb(v)]
		b.WriteString(fmt.Sprintf("%s = %q\n", v, cmd))
	}

	return b.String()
}
