package generate

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"rexrun.dev/rex/internal/detect"
)

// Stats generates a project report with stack info, file counts, and size.
func Stats(d *detect.Detection, root string) string {
	lines := []string{}
	lines = append(lines, "")
	lines = append(lines, "  ╭─────────────────────────────────────╮")
	lines = append(lines, "  │  🦖  PROJECT REPORT                 │")
	lines = append(lines, "  ╰─────────────────────────────────────╯")
	lines = append(lines, "")

	// Stack info
	mgrLabel := ""
	if d.PkgMgr != "" && d.PkgMgr != d.Stack {
		mgrLabel = " + " + d.PkgMgr
	}
	lines = append(lines, fmt.Sprintf("  stack        %s%s", d.Stack, mgrLabel))

	// File counts
	counts := countFiles(root, d.Stack)
	lines = append(lines, fmt.Sprintf("  files        %d", counts.files))
	lines = append(lines, fmt.Sprintf("  lines        %d", counts.lines))

	// Size
	size := dirSize(root)
	lines = append(lines, fmt.Sprintf("  size         %s", humanSize(size)))

	// Key files
	lines = append(lines, "")
	lines = append(lines, "  key files")
	for _, f := range keyFiles(root, d.Stack) {
		lines = append(lines, fmt.Sprintf("    %s", f))
	}

	lines = append(lines, "")
	lines = append(lines, fmt.Sprintf("  generated by rex  https://github.com/rexrun-dev/rex"))
	lines = append(lines, "")

	return strings.Join(lines, "\n")
}

type fileCounts struct {
	files int
	lines int
}

func countFiles(root, stack string) fileCounts {
	c := fileCounts{}
	exts := stackExts(stack)

	filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
		if err != nil || info.IsDir() {
			return nil
		}
		name := info.Name()
		// Skip hidden, vendor, node_modules
		if strings.Contains(path, "/.") || strings.Contains(path, "node_modules") ||
			strings.Contains(path, "vendor") || strings.Contains(path, "target") ||
			strings.Contains(path, "__pycache__") || strings.Contains(path, ".git") {
			return nil
		}
		for _, ext := range exts {
			if strings.HasSuffix(name, ext) {
				c.files++
				if data, err := os.ReadFile(path); err == nil {
					c.lines += strings.Count(string(data), "\n")
				}
				break
			}
		}
		return nil
	})
	return c
}

var extensions = []string{
	".go", ".rs", ".py", ".js", ".ts", ".jsx", ".tsx",
	".java", ".kt", ".rb", ".php", ".zig", ".ex", ".exs",
	".c", ".cpp", ".h", ".hpp", ".cs", ".swift",
	".html", ".css", ".scss", ".sass", ".less",
	".sql", ".yaml", ".yml", ".json", ".toml",
	".md", ".sh", ".bash", ".ps1",
}

func stackExts(stack string) []string {
	switch stack {
	case "go":
		return []string{".go"}
	case "node":
		return []string{".js", ".ts", ".jsx", ".tsx", ".mjs"}
	case "python":
		return []string{".py"}
	case "rust":
		return []string{".rs"}
	case "java":
		return []string{".java", ".kt"}
	case "ruby":
		return []string{".rb"}
	case "php":
		return []string{".php"}
	case "zig":
		return []string{".zig"}
	case "elixir":
		return []string{".ex", ".exs"}
	default:
		return extensions
	}
}

func dirSize(root string) int64 {
	var size int64
	filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
		if err == nil && !info.IsDir() {
			size += info.Size()
		}
		return nil
	})
	return size
}

func humanSize(bytes int64) string {
	const (
		KB = 1024
		MB = KB * 1024
		GB = MB * 1024
	)
	switch {
	case bytes >= GB:
		return fmt.Sprintf("%.1f GB", float64(bytes)/GB)
	case bytes >= MB:
		return fmt.Sprintf("%.1f MB", float64(bytes)/MB)
	case bytes >= KB:
		return fmt.Sprintf("%.1f KB", float64(bytes)/KB)
	default:
		return fmt.Sprintf("%d B", bytes)
	}
}

func keyFiles(root, stack string) []string {
	files := []string{}
	candidates := []string{}

	switch stack {
	case "go":
		candidates = []string{"go.mod", "main.go", "cmd/", "pkg/", "internal/", "Makefile"}
	case "node":
		candidates = []string{"package.json", "src/", "app/", "tsconfig.json", "vite.config.ts"}
	case "python":
		candidates = []string{"pyproject.toml", "main.py", "app.py", "requirements.txt"}
	case "rust":
		candidates = []string{"Cargo.toml", "src/main.rs", "src/lib.rs"}
	case "java":
		candidates = []string{"pom.xml", "build.gradle", "src/main/java/"}
	case "ruby":
		candidates = []string{"Gemfile", "config/routes.rb", "app/controllers/"}
	case "php":
		candidates = []string{"composer.json", "artisan", "index.php"}
	case "zig":
		candidates = []string{"build.zig", "src/main.zig"}
	case "elixir":
		candidates = []string{"mix.exs", "lib/", "config/"}
	}

	for _, c := range candidates {
		path := filepath.Join(root, c)
		if _, err := os.Stat(path); err == nil {
			files = append(files, c)
		}
	}
	return files
}
